
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8080:80"
    restart: unless-stopped
    volumes:
      - ./data:/app/data:rw
    environment:
      - NODE_ENV=production
    networks:
      - default

networks:
  default:
    driver: bridge
