
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8080:80"
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
